/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zh_idreader_IDReader */

#ifndef _Included_com_example_zh_idreader_IDReader
#define _Included_com_example_zh_idreader_IDReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zh_idreader_IDReader
 * Method:    RfidOpenDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_zh_1idreader_IDReader_RfidOpenDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zh_idreader_IDReader
 * Method:    RfidCloseDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_zh_1idreader_IDReader_RfidCloseDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zh_idreader_IDReader
 * Method:    RfidReadEnable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_zh_1idreader_IDReader_RfidReadEnable
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zh_idreader_IDReader
 * Method:    RfidReadDisable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_zh_1idreader_IDReader_RfidReadDisable
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zh_idreader_IDReader
 * Method:    RfidSetKeyAndMode
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_zh_1idreader_IDReader_RfidSetKeyAndMode
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_zh_idreader_IDReader
 * Method:    RfidSetSecNumAndBlockNum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_zh_1idreader_IDReader_RfidSetSecNumAndBlockNum
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_zh_idreader_IDReader
 * Method:    RfidReadCardIDSecAndBlock
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_example_zh_1idreader_IDReader_RfidReadCardIDSecAndBlock
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
